# Generated by Django 5.0.3 on 2026-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('client_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'client',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('defect_code', models.CharField(max_length=50, unique=True, verbose_name='不良项编码')),
                ('defect_name', models.CharField(max_length=100, verbose_name='不良项名称')),
                ('defect_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='不良项类型')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '不良项',
                'verbose_name_plural': '不良项',
                'db_table': 'defect',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('procedure_code', models.CharField(max_length=50, unique=True, verbose_name='工序编码')),
                ('procedure_name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('procedure_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='工序类型')),
                ('standard_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='标准工时(分钟)')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'db_table': 'procedure_info',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRoute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route_code', models.CharField(max_length=50, unique=True, verbose_name='工艺路线编码')),
                ('route_name', models.CharField(max_length=100, verbose_name='工艺路线名称')),
                ('product_id', models.BigIntegerField(blank=True, null=True, verbose_name='产品ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品名称')),
                ('procedures', models.JSONField(default=list, verbose_name='工序列表')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工艺路线',
                'verbose_name_plural': '工艺路线',
                'db_table': 'process_route',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品类型')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'product',
                'ordering': ['-create_time'],
            },
        ),
    ]
