# Generated by Django 5.0.3 on 2026-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_id', models.BigIntegerField(verbose_name='工单ID')),
                ('sheet_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='工单编码')),
                ('task_id', models.BigIntegerField(verbose_name='任务ID')),
                ('task_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='任务编码')),
                ('procedure_id', models.BigIntegerField(verbose_name='工序ID')),
                ('procedure_name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('procedure_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='工序编码')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='报工数量')),
                ('defect_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='不良数量')),
                ('booking_time', models.DateTimeField(verbose_name='报工时间')),
                ('operator_id', models.BigIntegerField(verbose_name='操作员ID')),
                ('operator_name', models.CharField(max_length=50, verbose_name='操作员姓名')),
                ('defect_details', models.JSONField(blank=True, default=list, null=True, verbose_name='不良明细')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '报工记录',
                'verbose_name_plural': '报工记录',
                'db_table': 'job_booking',
                'ordering': ['-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_code', models.CharField(max_length=50, unique=True, verbose_name='工单编码')),
                ('sheet_name', models.CharField(max_length=200, verbose_name='工单名称')),
                ('product_id', models.BigIntegerField(verbose_name='产品ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品编码')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划数量')),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='完成数量')),
                ('defect_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='不良数量')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='计划结束时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('0', '待生产'), ('1', '生产中'), ('2', '已完成'), ('3', '已取消')], default='0', max_length=1, verbose_name='工单状态')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('process_route_id', models.BigIntegerField(blank=True, null=True, verbose_name='工艺路线ID')),
                ('process_route_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='工艺路线名称')),
                ('client_id', models.BigIntegerField(blank=True, null=True, verbose_name='客户ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='客户名称')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '生产工单',
                'verbose_name_plural': '生产工单',
                'db_table': 'sheet',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_id', models.BigIntegerField(verbose_name='工单ID')),
                ('sheet_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='工单编码')),
                ('task_code', models.CharField(max_length=50, verbose_name='任务编码')),
                ('procedure_id', models.BigIntegerField(verbose_name='工序ID')),
                ('procedure_name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('procedure_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='工序编码')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='任务数量')),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='完成数量')),
                ('defect_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='不良数量')),
                ('status', models.CharField(choices=[('0', '待执行'), ('1', '执行中'), ('2', '已完成')], default='0', max_length=1, verbose_name='任务状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '生产任务',
                'verbose_name_plural': '生产任务',
                'db_table': 'task',
                'ordering': ['sort_order', '-create_time'],
            },
        ),
    ]
