# Generated by Django 5.0.3 on 2026-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_code', models.CharField(max_length=50, unique=True, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='物料类型')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存数量')),
                ('safety_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='安全库存')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('supplier_id', models.BigIntegerField(blank=True, null=True, verbose_name='供应商ID')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商名称')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'db_table': 'material',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SheetMaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_id', models.BigIntegerField(verbose_name='工单ID')),
                ('sheet_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='工单编码')),
                ('material_id', models.BigIntegerField(verbose_name='物料ID')),
                ('material_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('plan_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际数量')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工单物料',
                'verbose_name_plural': '工单物料',
                'db_table': 'sheet_material',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=50, unique=True, verbose_name='供应商编码')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账号')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态')),
                ('tenant_id', models.BigIntegerField(blank=True, null=True, verbose_name='租户ID')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'purveyor_info',
                'ordering': ['-create_time'],
            },
        ),
    ]
